Test1
mnjaggah/office_space_allocation pull request #1
Opened 2017-02-28 11:18 UTC by mnjaggah

TestCases for room creation @kevintumbo @gdp254

2017-02-28 12:02 UTC, kevintumbo approved these changes

2017-02-28 15:58 UTC, jomomg commented
* I don't think you should test whether `self.office_space` is an instance of `OfficeSpace` class since you have already explicitly made it an instance in the `setUp` function. So the test will never fail. 
* Same for `self.living_space`
* Otherwise, I think the rest is OK

2017-03-01 07:19 UTC, jomomg commented
```Python
def test_person_type(self):
	person = Person() # You don't need this since you've already instantiated in the 'setUp' function
	post = Person.position # Typo: should be 'post = self.person.position'
	self.assertEqual('FELLOW' or 'STAFF', post,  
			msg = 'Wrong position specified') 
```

2017-03-01 07:44 UTC, kevintumbo requested changes
`person = Person()   #remove since already initialized in set up'

2017-03-01 08:40 UTC, mnjaggah commented on test_cases/tests.py
> +		post = self.person.position
Fixed test definition as suggested by @kevintumbo

2017-03-01 14:46 UTC, GDP254 commented on test_cases/tests.py
> +
3 spaces to the next method. This is inconsistent with your previous spacing.

2017-03-01 14:59 UTC, GDP254 commented on test_cases/tests.py
> +		self.assertRaises(ValueError, self.office_space.create_new, 111)
Your function name is descriptive but, it does not match its contents in my opinion. I think `test_officespace_rejects_int` would be better.

2017-03-01 15:10 UTC, GDP254 commented
Git commits should be in imperative form. I found this section of the linked reference to be helpful:

> A properly formed Git commit subject line should always be able to complete the following sentence:
> 
>     If applied, this commit will your subject line here
> 
> For example:
> 
>     If applied, this commit will refactor subsystem X for readability
>     If applied, this commit will update getting started documentation
>     If applied, this commit will remove deprecated methods
>     If applied, this commit will release version 1.0.0
>     If applied, this commit will merge pull request #123 from user/branch
> 
> Notice how this doesn’t work for the other non-imperative forms:
> 
>     If applied, this commit will fixed bug with Y
>     If applied, this commit will changing behavior of X
>     If applied, this commit will more fixes for broken stuff
>     If applied, this commit will sweet new API methods
> 
>     Remember: Use of the imperative is important only in the subject line. You can relax this restriction when you’re writing the body.
> 

Source: https://chris.beams.io/posts/git-commit/

2017-03-01 17:05 UTC, kevintumbo approved these changes

2017-03-01 18:51 UTC, mnjaggah commented
thanks for the link @GDP254  i totally missed the imperative nature of commit messages on that last one

2017-03-01 19:54 UTC, maquchizi approved these changes
This is good work. Please consider the following in addition to what your peers raised:
1. PEP8 coding standards for Python (line spacing especially)
2. The test file is getting quite large. Perhaps you could break it out into separate files for readability

2017-03-02 11:57 UTC, merged